# Generated by Django 5.2 on 2025-06-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('capacidad_carga', models.IntegerField()),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
            ],
            options={
                'db_table': 'vehiculo',
                'permissions': [('crear_Vehiculo', 'Puede crear vehículo'), ('editar_Vehiculo', 'Puede editar vehículo'), ('eliminar_Vehiculo', 'Puede eliminar vehículo'), ('ver_Vehiculo', 'Puede ver vehículo')],
                'default_permissions': (),
            },
        ),
    ]
