# Generated by Django 5.2 on 2025-06-20 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('licencia', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribuidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'distribuidor',
                'permissions': [('crear_Distribuidor', 'Puede crear distribuidor'), ('editar_Distribuidor', 'Puede editar distribuidor'), ('eliminar_Distribuidor', 'Puede eliminar distribuidor'), ('ver_Distribuidor', 'Puede ver distribuidor')],
                'default_permissions': (),
            },
        ),
    ]
