# Generated by Django 5.2 on 2025-06-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'color',
                'permissions': [('crear_Color', 'Puede crear color'), ('editar_Color', 'Puede editar color'), ('eliminar_Color', 'Puede eliminar color'), ('ver_Color', 'Puede ver color')],
                'default_permissions': (),
            },
        ),
    ]
