# Generated by Django 5.2 on 2025-06-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'marca',
                'permissions': [('crear_Marca', 'Puede crear marca'), ('editar_Marca', 'Puede editar marca'), ('eliminar_Marca', 'Puede eliminar marca'), ('ver_Marca', 'Puede ver marca')],
                'default_permissions': (),
            },
        ),
    ]
