# Generated by Django 5.2 on 2025-06-27 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
        ('producto_variante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='carrito.carrito')),
                ('producto_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='producto_variante.producto_variante')),
            ],
            options={
                'db_table': 'detalle_carrito',
                'permissions': [('crear_detalle_carrito', 'Puede crear detalle de carrito'), ('editar_detalle_carrito', 'Puede editar detalle de carrito'), ('eliminar_detalle_carrito', 'Puede eliminar detalle de carrito'), ('ver_detalle_carrito', 'Puede ver detalle de carrito')],
                'default_permissions': (),
            },
        ),
    ]
