# Generated by Django 5.2 on 2025-07-10 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('detalle_carrito', '0001_initial'),
        ('producto_variante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_carrito', to='carrito.carrito'),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='producto_variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_carrito', to='producto_variante.producto_variante'),
        ),
    ]
