# Generated by Django 5.2 on 2025-06-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('color', '0001_initial'),
        ('producto', '0001_initial'),
        ('talla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_SKU', models.CharField(max_length=10)),
                ('precio_compra', models.FloatField(max_length=5)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='color.color')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
                ('talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talla.talla')),
            ],
            options={
                'db_table': 'producto_variante',
                'permissions': [('crear_Producto_Variante', 'Puede crear producto_variante'), ('editar_Producto_Variante', 'Puede editar producto_variante'), ('eliminar_Producto_Variante', 'Puede eliminar producto_variante'), ('ver_Producto_Variante', 'Puede ver producto_variante')],
                'default_permissions': (),
            },
        ),
    ]
