# Generated by Django 5.2 on 2025-07-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nota_venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('qr', 'QR'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('referencia_qr', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante_qr', models.ImageField(blank=True, null=True, upload_to='pagos/qr/')),
                ('ultimos_digitos_tarjeta', models.CharField(blank=True, max_length=4, null=True)),
                ('tipo_tarjeta', models.CharField(blank=True, max_length=20, null=True)),
                ('nota_venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='nota_venta.notaventa')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
    ]
