# Generated by Django 5.2 on 2025-07-13 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direccion', '0002_alter_direccion_latitud_alter_direccion_longitud'),
        ('distribuidor', '0001_initial'),
        ('nota_venta', '0002_alter_notaventa_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('en_camino', 'En camino'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('direccion_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='direccion.direccion')),
                ('nota_venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden', to='nota_venta.notaventa')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='distribuidor.distribuidor')),
            ],
        ),
    ]
