# Generated by Django 5.2 on 2025-06-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('producto_variante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.inventario')),
                ('producto_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto_variante.producto_variante')),
            ],
            options={
                'db_table': 'detalle_inventario',
                'permissions': [('crear_detalle_inventario', 'Puede crear detalle_inventario'), ('editar_detalle_inventario', 'Puede editar detalle_inventario'), ('eliminar_detalle_inventario', 'Puede eliminar detalle_inventario'), ('ver_detalle_inventario', 'Puede ver detalle_inventario')],
                'default_permissions': (),
            },
        ),
    ]
