# Generated by Django 5.2 on 2025-06-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_producto', models.CharField(max_length=256)),
                ('cantidad_total', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'permissions': [('crear_Inventario', 'Puede crear Inventario'), ('editar_Inventario', 'Puede editar Inventario'), ('eliminar_Inventario', 'Puede eliminar Inventario'), ('ver_Inventario', 'Puede ver Inventario')],
                'default_permissions': (),
            },
        ),
    ]
