# Generated by Django 5.2 on 2025-07-10 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='cliente.cliente')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='direccion.direccion')),
            ],
            options={
                'db_table': 'cliente_direccion',
                'permissions': [('crear_ClienteDireccion', 'Puede crear cliente direccion'), ('editar_ClienteDireccion', 'Puede editar cliente direccion'), ('eliminar_ClienteDireccion', 'Puede eliminar cliente direccion'), ('ver_ClienteDireccion', 'Puede ver cliente direccion')],
                'default_permissions': (),
            },
        ),
    ]
