# Generated by Django 5.2 on 2025-07-10 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nota_venta', '0001_initial'),
        ('producto_variante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleNotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nota_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_nota_venta', to='nota_venta.notaventa')),
                ('producto_variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_nota_venta', to='producto_variante.producto_variante')),
            ],
            options={
                'db_table': 'detalle_nota_venta',
                'permissions': [('crear_detalle_nota_venta', 'Puede crear detalle de nota de venta'), ('editar_detalle_nota_venta', 'Puede editar detalle de nota de venta'), ('eliminar_detalle_nota_venta', 'Puede eliminar detalle de nota de venta'), ('ver_detalle_nota_venta', 'Puede ver detalle de nota de venta')],
                'default_permissions': (),
            },
        ),
    ]
