# Generated by Django 5.2 on 2025-07-12 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('detalle_inventario', '0001_initial'),
        ('producto_variante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_reservado', to='cliente.cliente')),
                ('detalle_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_reservado', to='detalle_inventario.detalle_inventario')),
                ('producto_variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_reservado', to='producto_variante.producto_variante')),
            ],
            options={
                'db_table': 'inventario_reservado',
                'permissions': [('crear_inventario_reservado', 'Puede crear inventario reservado'), ('editar_inventario_reservado', 'Puede editar inventario reservado'), ('eliminar_inventario_reservado', 'Puede eliminar inventario reservado'), ('ver_inventario_reservado', 'Puede ver inventario reservado')],
                'default_permissions': (),
            },
        ),
    ]
