"""
Django settings for qualityShoes_Django project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from datetime import timedelta

# from pathlib import Path

# 1. Configuración de rutas


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))  # Añade el directorio raíz al PYTHONPATH


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-_fmv*qlr=1)h=-*p$1ctx6l^c7d1#wt3ew1vcq-u(13(9^bqa)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # APPS INSTALADAS
    "rest_framework",
    "coreapi",
    "Api.marca",
    "Api.talla",
    "Api.color",
    "Api.producto",
    #"Api.producto_color",
    #"Api.usuario",
    "Api.producto_variante",
    "Api.permiso",
    "Api.inventario",
    "Api.detalle_inventario",
    "Api.imagen",
    "Api.vehiculo",
    "Api.distribuidor",
    "Api.vehiculo_distribuidor",
    "Api.carrito",
    "Api.detalle_carrito",
    "Api.nota_venta",
    "Api.detalle_nota_venta",
    "Api.cliente",
    "Api.direccion",
    "Api.cliente_direccion",
    "Api.inventario_reservado",
    "Api.pago",
    "Api.ubicacion_distribuidor",
    "Api.rol",
    "Api.orden",
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe estar al principio
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "qualityShoes_Django.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "qualityShoes_Django.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        #"ENGINE": "django.db.backends.postgresql",
        #"NAME": "SIG_BACKEND",  # Nombre de la DB en PostgreSQL
        #"USER": "postgres",  # Usuario de PostgreSQL
        #"PASSWORD": "root",  # Contraseña del usuario
        #"HOST": "localhost",  # IP si está en otro servidor
        #"PORT": "5432",  # Puerto por defecto de PostgreSQL



        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',                      # Database name
        'USER': 'postgres',                      # Database user
        'PASSWORD': 'tGdByOkkAJzIVQEsNgFkfyBhSSSKaIgw',  # Database password
        'HOST': 'hopper.proxy.rlwy.net',         # Database host
        'PORT': '58293', 
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # LA LINEA DE ABAJO PROTEGE TODAS LAS APIS CON  JWT #
    #"DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}

# settings.py
MEDIA_URL = "/media/"  # URL pública para archivos multimedia
MEDIA_ROOT = os.path.join(BASE_DIR, "media")  # Ruta en el sistema de archivos

#AUTH_USER_MODEL = 'Api_usuario.Usuario'  # Nota el underscore

LANGUAGE_CODE = 'es-es'
USE_I18N = True
USE_L10N = True


# Permitir todos los orígenes (solo para desarrollo)
CORS_ALLOW_ALL_ORIGINS = True

# Para desarrollo (permite todas las IPs locales)
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.1.136',  # Agrega tu IP local
    '*',  # Solo para desarrollo, NO usar en producción
]


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),   # Cambia 30 por los minutos que desees
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),      # Cambia 7 por los días que desees
    # Puedes agregar más configuraciones si lo necesitas
}

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = 'pk_test_51QVuWGCHs37kbJSiycZNy4C7WBXxlUPEJjOE177w4wefPrqRdcUItjelS7uTuwBKzwwK945nDe7j6jjecg0EfnuT00T9L9EHlw'
STRIPE_SECRET_KEY = 'rk_test_51QVuWGCHs37kbJSi0ZRczmZhJA7fKTH7VwJOhA6GpAygpO7vtNnrRl9WwZCdG6BMeH0MrxnFU82BHwpon7xzdQSc002blpqdme'
STRIPE_WEBHOOK_SECRET = 'whsec_YwLbeecwzfB2YQLLmCHveVinCjUn9rP1'
GOOGLE_MAPS_API_KEY='AIzaSyDT4RYNcUdQ6279kqNgHV1Tgn2d9biKKKY'
# Configuración para archivos estáticos en producción
STATIC_ROOT = str(BASE_DIR / 'staticfiles')
