# Generated by Django 5.2 on 2025-07-10 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('ci_nit', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cliente',
                'permissions': [('crear_Cliente', 'Puede crear cliente'), ('editar_Cliente', 'Puede editar cliente'), ('eliminar_Cliente', 'Puede eliminar cliente'), ('ver_Cliente', 'Puede ver cliente')],
                'default_permissions': (),
            },
        ),
    ]
