# Generated by Django 5.2 on 2025-07-13 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribuidor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionDistribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('distribuidor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='distribuidor.distribuidor')),
            ],
        ),
    ]
