# Generated by Django 5.2 on 2025-06-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=256)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marca.marca')),
            ],
            options={
                'db_table': 'producto',
                'permissions': [('crear_Productos', 'Puede crear productos'), ('editar_Productos', 'Puede editar productos'), ('eliminar_Productos', 'Puede eliminar productos'), ('ver_Productos', 'Puede ver productos')],
                'default_permissions': (),
            },
        ),
    ]
