# Generated by Django 5.2 on 2025-07-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='latitud',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='longitud',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud'),
        ),
    ]
