# Generated by Django 5.2 on 2025-06-27 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carrito',
                'permissions': [('crear_carrito', 'Puede crear carrito'), ('editar_carrito', 'Puede editar carrito'), ('eliminar_carrito', 'Puede eliminar carrito'), ('ver_carrito', 'Puede ver carrito')],
                'default_permissions': (),
            },
        ),
    ]
