# Generated by Django 5.2 on 2025-06-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribuidor', '0001_initial'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoDistribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuidor', to='distribuidor.distribuidor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='vehiculo.vehiculo')),
            ],
            options={
                'db_table': 'vehiculo_distribuidor',
                'permissions': [('crear_VehiculoDistribuidor', 'Puede crear asignación de vehículo'), ('editar_VehiculoDistribuidor', 'Puede editar asignación de vehículo'), ('eliminar_VehiculoDistribuidor', 'Puede eliminar asignación de vehículo'), ('ver_VehiculoDistribuidor', 'Puede ver asignación de vehículo')],
                'default_permissions': (),
                'unique_together': {('vehiculo', 'distribuidor', 'activo')},
            },
        ),
    ]
